// <auto-generated />
using System;
using Deuna.Identity.Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deuna.Identity.Service.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260926154807_AgregarRecursosYPermisosUsuarios")]
    partial class AgregarRecursosYPermisosUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.AuditoriaAdministrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EntidadAfectada")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("PerfilAdministradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Accion")
                        .HasDatabaseName("ix_auditoria_admin_accion");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_auditoria_admin_fecha");

                    b.HasIndex("PerfilAdministradorId")
                        .HasDatabaseName("ix_auditoria_admin");

                    b.ToTable("auditoria_administrador", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.CodigoAutorizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("EmitidoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RestauranteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_codigos_autorizacion_codigo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_codigos_autorizacion_estado");

                    b.HasIndex("RestauranteId")
                        .HasDatabaseName("ix_codigos_autorizacion_restaurante");

                    b.ToTable("codigos_autorizacion", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.DocumentoRepartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PerfilRepartidorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRepartidorId")
                        .HasDatabaseName("ix_documentos_repartidor");

                    b.HasIndex("PerfilRepartidorId", "Tipo")
                        .HasDatabaseName("ix_documentos_repartidor_tipo");

                    b.ToTable("documentos_repartidor", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.HorarioAtencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("PerfilRestauranteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRestauranteId")
                        .HasDatabaseName("ix_horarios_restaurante");

                    b.HasIndex("PerfilRestauranteId", "DiaSemana")
                        .IsUnique()
                        .HasDatabaseName("ix_horarios_restaurante_dia");

                    b.ToTable("horarios_atencion", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.MetodoPagoRestaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PerfilRestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRestauranteId")
                        .HasDatabaseName("ix_metodos_pago_restaurante");

                    b.ToTable("metodos_pago_restaurante", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilAdministrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("JefeDirectoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_perfiles_admin_activo");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfiles_admin_usuario");

                    b.ToTable("perfiles_administrador", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CiudadOperacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<int>("EntregasCanceladas")
                        .HasColumnType("integer");

                    b.Property<int>("EntregasCompletadas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaVencimientoLicencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoLicencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalEntregas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_perfiles_repartidor_activo");

                    b.HasIndex("Disponible")
                        .HasDatabaseName("ix_perfiles_repartidor_disponible");

                    b.HasIndex("NumeroLicencia")
                        .IsUnique()
                        .HasDatabaseName("ix_perfiles_repartidor_licencia")
                        .HasFilter("\"NumeroLicencia\" IS NOT NULL");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfiles_repartidor_usuario");

                    b.ToTable("perfiles_repartidor", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceptaPedidos")
                        .HasColumnType("boolean");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DireccionSede")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("HoraApertura")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("interval");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_perfiles_restaurante_activo");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("ix_perfiles_restaurante_nit");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfiles_restaurante_usuario");

                    b.ToTable("perfiles_restaurante", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PermisoAdministrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Concedido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PerfilAdministradorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permiso")
                        .HasColumnType("integer");

                    b.Property<string>("Recurso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerfilAdministradorId")
                        .HasDatabaseName("ix_permisos_admin");

                    b.HasIndex("PerfilAdministradorId", "Permiso", "Recurso")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_admin_unique");

                    b.ToTable("permisos_administrador", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PermisoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Concedido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Permiso")
                        .HasColumnType("integer");

                    b.Property<string>("Recurso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_permisos_usuarios");

                    b.HasIndex("UsuarioId", "Permiso", "Recurso", "Accion")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_usuarios_unique");

                    b.ToTable("permisos_usuarios", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acciones")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Servicio", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_recursos_servicio_clave");

                    b.ToTable("recursos", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_usuarios_deleted");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_usuarios_active");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_phone")
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.VehiculoRepartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnioFabricacion")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaVencimientoSOAT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroSOAT")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroTarjetaPropiedad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PerfilRepartidorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRepartidorId")
                        .HasDatabaseName("ix_vehiculos_repartidor");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ix_vehiculos_placa")
                        .HasFilter("\"Placa\" IS NOT NULL");

                    b.ToTable("vehiculos_repartidor", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.ZonaCoberturaRepartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PerfilRepartidorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRepartidorId")
                        .HasDatabaseName("ix_zonas_cob_repartidor");

                    b.ToTable("zonas_cobertura_repartidor", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.ZonaCoberturaRestaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PedidoMinimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("PerfilRestauranteId")
                        .HasColumnType("uuid");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRestauranteId")
                        .HasDatabaseName("ix_zonas_cob_restaurante");

                    b.HasIndex("PerfilRestauranteId", "NombreZona")
                        .IsUnique()
                        .HasDatabaseName("ix_zonas_cob_restaurante_nombre");

                    b.ToTable("zonas_cobertura_restaurante", (string)null);
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.AuditoriaAdministrador", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilAdministrador", "PerfilAdministrador")
                        .WithMany("Auditorias")
                        .HasForeignKey("PerfilAdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAdministrador");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.DocumentoRepartidor", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", "PerfilRepartidor")
                        .WithMany("Documentos")
                        .HasForeignKey("PerfilRepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRepartidor");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.HorarioAtencion", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", "PerfilRestaurante")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("PerfilRestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRestaurante");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.MetodoPagoRestaurante", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", "PerfilRestaurante")
                        .WithMany("MetodosPago")
                        .HasForeignKey("PerfilRestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRestaurante");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilAdministrador", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.Usuario", "Usuario")
                        .WithOne("PerfilAdministrador")
                        .HasForeignKey("Deuna.Identity.Service.Models.Domain.PerfilAdministrador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.Usuario", "Usuario")
                        .WithOne("PerfilRepartidor")
                        .HasForeignKey("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.Usuario", "Usuario")
                        .WithOne("PerfilRestaurante")
                        .HasForeignKey("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PermisoAdministrador", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilAdministrador", "PerfilAdministrador")
                        .WithMany("Permisos")
                        .HasForeignKey("PerfilAdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAdministrador");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PermisoUsuario", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.RefreshToken", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.VehiculoRepartidor", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", "PerfilRepartidor")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PerfilRepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRepartidor");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.ZonaCoberturaRepartidor", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", "PerfilRepartidor")
                        .WithMany("ZonasCobertura")
                        .HasForeignKey("PerfilRepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRepartidor");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.ZonaCoberturaRestaurante", b =>
                {
                    b.HasOne("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", "PerfilRestaurante")
                        .WithMany("ZonasCobertura")
                        .HasForeignKey("PerfilRestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRestaurante");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilAdministrador", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilRepartidor", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Vehiculos");

                    b.Navigation("ZonasCobertura");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.PerfilRestaurante", b =>
                {
                    b.Navigation("HorariosAtencion");

                    b.Navigation("MetodosPago");

                    b.Navigation("ZonasCobertura");
                });

            modelBuilder.Entity("Deuna.Identity.Service.Models.Domain.Usuario", b =>
                {
                    b.Navigation("PerfilAdministrador");

                    b.Navigation("PerfilRepartidor");

                    b.Navigation("PerfilRestaurante");

                    b.Navigation("Permisos");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
