// <auto-generated />
using System;
using Deuna.Feedback.Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deuna.Feedback.Service.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    [Migration("20260923231032_AddNivel2YViralidadWhatsApp")]
    partial class AddNivel2YViralidadWhatsApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deuna.Feedback.Service.Models.FeedbackComentarioFoto", b =>
                {
                    b.Property<Guid>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComentarioTexto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UrlFotoEvidencia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("EncuestaId");

                    b.ToTable("feedback_comentarios_fotos");
                });

            modelBuilder.Entity("Deuna.Feedback.Service.Models.FeedbackDetalleCriterio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("EncuestaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId", "Criterio")
                        .IsUnique();

                    b.ToTable("feedback_detalle_criterios", null, t =>
                        {
                            t.HasCheckConstraint("CK_feedback_detalle_criterios_puntaje", "\"Puntaje\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Deuna.Feedback.Service.Models.FeedbackEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeseaRecomendar")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<int>("RatingGeneralComida")
                        .HasColumnType("integer");

                    b.Property<int>("RatingServicioRepartidor")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("feedback_encuestas", null, t =>
                        {
                            t.HasCheckConstraint("CK_feedback_encuestas_rating_comida", "\"RatingGeneralComida\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_feedback_encuestas_rating_repartidor", "\"RatingServicioRepartidor\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Deuna.Feedback.Service.Models.FeedbackViralWhatsApp", b =>
                {
                    b.Property<Guid>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCompartido")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("FechaCompartido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueCompartido")
                        .HasColumnType("boolean");

                    b.HasKey("EncuestaId");

                    b.HasIndex("CodigoCompartido")
                        .IsUnique();

                    b.HasIndex("FueCompartido");

                    b.ToTable("feedback_viral_whatsapp");
                });

            modelBuilder.Entity("Deuna.Feedback.Service.Models.PedidoReplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.HasIndex("RestauranteId");

                    b.ToTable("pedidos_replicados");
                });

            modelBuilder.Entity("Deuna.Feedback.Service.Models.RepartidorReplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CiudadOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.ToTable("repartidores_replicados");
                });

            modelBuilder.Entity("Deuna.Feedback.Service.Models.RestauranteReplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.ToTable("restaurantes_replicados");
                });
#pragma warning restore 612, 618
        }
    }
}
