// <auto-generated />
using System;
using Deuna.Orders.Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deuna.Orders.Service.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260925211500_AddCalificacionesReplicadas")]
    partial class AddCalificacionesReplicadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deuna.Orders.Service.Models.AsignacionReplicada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoAsignacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLlegadaLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSalidaRuta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PedidoId", "RepartidorId", "FechaAsignacion")
                        .IsUnique();

                    b.ToTable("pedidos_asignados_repartidor");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.CalificacionReplicada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalificacionDomiciliario")
                        .HasColumnType("integer");

                    b.Property<int>("CalificacionRestaurante")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.ToTable("calificaciones_replicadas");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.ContactoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("contactos_pedido");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.DireccionEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Interior")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.HasKey("Id");

                    b.HasIndex("Ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "GIST");

                    b.ToTable("direcciones_entrega");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.HorarioAtencionReplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("RestauranteReplicadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteReplicadoId");

                    b.ToTable("horarios_atencion_replicados");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("items_pedido");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DireccionEntregaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaListo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPreparacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasCliente")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NotasRestaurante")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TokenQrEntrega")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("TokenQrLocal")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DireccionEntregaId");

                    b.HasIndex("Estado");

                    b.HasIndex("RestauranteId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.RepartidorReplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CiudadOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("repartidores_replicados");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.RestauranteReplicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceptaPedidos")
                        .HasColumnType("boolean");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DireccionSede")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan>("HoraApertura")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("interval");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("RadioCoberturaKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Ciudad");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("Ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "GIST");

                    b.ToTable("restaurantes_replicados");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.TarifaAplicada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostoAdicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoPorKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DetalleCalculo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("DistanciaKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoTarifa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalCalculado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("tarifas_aplicadas");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.ZonaCoberturaReplicada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Polygon>("Geom")
                        .HasColumnType("geography (polygon)");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PedidoMinimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("RestauranteReplicadoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("RestauranteReplicadoId");

                    b.ToTable("zonas_cobertura_replicadas");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.ContactoPedido", b =>
                {
                    b.HasOne("Deuna.Orders.Service.Models.Pedido", "Pedido")
                        .WithMany("Contactos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.HorarioAtencionReplicado", b =>
                {
                    b.HasOne("Deuna.Orders.Service.Models.RestauranteReplicado", "RestauranteReplicado")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("RestauranteReplicadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestauranteReplicado");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.ItemPedido", b =>
                {
                    b.HasOne("Deuna.Orders.Service.Models.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.Pedido", b =>
                {
                    b.HasOne("Deuna.Orders.Service.Models.DireccionEntrega", "DireccionEntrega")
                        .WithMany("Pedidos")
                        .HasForeignKey("DireccionEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Deuna.Orders.Service.Models.RestauranteReplicado", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DireccionEntrega");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.TarifaAplicada", b =>
                {
                    b.HasOne("Deuna.Orders.Service.Models.Pedido", "Pedido")
                        .WithOne("Tarifa")
                        .HasForeignKey("Deuna.Orders.Service.Models.TarifaAplicada", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.ZonaCoberturaReplicada", b =>
                {
                    b.HasOne("Deuna.Orders.Service.Models.RestauranteReplicado", "RestauranteReplicado")
                        .WithMany("ZonasCobertura")
                        .HasForeignKey("RestauranteReplicadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestauranteReplicado");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.DireccionEntrega", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.Pedido", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Items");

                    b.Navigation("Tarifa");
                });

            modelBuilder.Entity("Deuna.Orders.Service.Models.RestauranteReplicado", b =>
                {
                    b.Navigation("HorariosAtencion");

                    b.Navigation("ZonasCobertura");
                });
#pragma warning restore 612, 618
        }
    }
}
